language: go
go:
  - tip
services:
  - rabbitmq
before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script: go test -v -race -coverprofile=coverage.out && goveralls -coverprofile=coverage.out -service=travis-ci
